Add a section on pair programming
the-collab-lab/smart-shopping-list-deprecated pull request #29
Opened 2019-11-11 05:58 UTC by stacietaylorcima

## Description 

This PR adds a section to the Project Brief on Pair Programming. This is a very important part of Collab Lab and adding some more detail to the Project Brief will help members launch into the project with more confidence. 

## Goals

There were three important things I want to convey here so that our team knows what to expect.

1. The idea that everyone is expected to pair live with their partner during the week. I teetered on the idea of saying something like "at least one time per week" but decided that didn't seem totally necessary. Thoughts here?
2. Why pair programming is great and everyone should be excited for it!
3. A high-level of what pair programming looks like at Collab Lab.

Let me know what you think here! 🤗

2019-11-11 06:05 UTC, stacietaylorcima commented on PROJECT-BRIEF.md
> +A portion of your dedicated hours each week will be spent [pair programming](https://www.freecodecamp.org/news/how-remote-pair-programming-works-and-why-it-can-change-your-life-cd7b767dc60f/) with yo
This isn't an article that I had a strong pull towards, it just seemed like the most digestible, most on-brand one I found after a short search for articles on pair programming. LMK if you have good resources here. I def wanna link to somewhere they can learn more.

2019-11-13 00:29 UTC, segdeha requested changes
Looks great! My only requested changes are around using proper/curly/smart quote marks. Thanks for doing this!

2019-11-13 00:29 UTC, segdeha commented on PROJECT-BRIEF.md
> +A portion of your dedicated hours each week will be spent [pair programming](https://www.freecodecamp.org/news/how-remote-pair-programming-works-and-why-it-can-change-your-life-cd7b767dc60f/) with yo
That looks good enough to use to start with to me! It covers the main points such as drive/navigator and is easy to scan and digest

2019-11-13 00:29 UTC, segdeha commented on PROJECT-BRIEF.md
> +There is no one "right" way to pair program, but in general, you will meet with your partner on Zoom to work through the story or task you've chosen for that week. You're encouraged to test out some
I’m a stickler for using the correct quote marks, so I prefer `“right”` to `"right"` and `you’re` to `you're`. Thanks for indulging my pedantic-ness!

2019-11-13 03:07 UTC, segdeha submitted a review, later dismissed
Just one little change that I missed the first time through. Thank you!

2019-11-13 03:07 UTC, segdeha commented on PROJECT-BRIEF.md
> +A portion of your dedicated hours each week will be spent [pair programming](https://www.freecodecamp.org/news/how-remote-pair-programming-works-and-why-it-can-change-your-life-cd7b767dc60f/) with yo
Oh, whoops, should have caught this the first time. Can you please replace ` -- ` with `—` ← that’s an “em” dash, which is the proper typographic mark for delineating a section of a sentence like this one.

2019-11-13 03:07 UTC, segdeha commented on PROJECT-BRIEF.md
> +A portion of your dedicated hours each week will be spent [pair programming](https://www.freecodecamp.org/news/how-remote-pair-programming-works-and-why-it-can-change-your-life-cd7b767dc60f/) with yo
(I realize this level of attention to detail is overkill for a README, but it’s the kind of thing I can’t help but notice.) 😬

2019-11-13 03:07 UTC, segdeha commented on PROJECT-BRIEF.md
> +There is no one “right” way to pair program, but in general, you will meet with your partner on Zoom to work through the story or task you’ve chosen for that week. You’re encouraged to test out some
Lovely! 👏🏻👏🏻👏🏻

2019-11-13 03:07 UTC, segdeha commented on PROJECT-BRIEF.md
> +![gif of a My Little Pony pulling on goggles, with a determined look on their face, saying, “Let’s do this”.](http://giphygifs.s3.amazonaws.com/media/PuWNMebKGIKNG/giphy.gif)
Niiiiiiice!!! 😍🤩🥳

2019-11-13 04:38 UTC, merged